server:
  port: 8888
  #自定义配置项
#mytest1: 小黑

 #配置数据库连接
#yml的语法格式 key: value  注意中间是冒号+空格
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8
    username: root
    password: root

#数据库
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/demo1?characterEncoding=utf8
#    username: root
#    password: root
#字符串
#myStirng1: 哈喽\n呀
#myStirng2: '哈喽\n呀'
#myStirng3: "哈喽\n呀"

#student:
#  id: 1
#  name: zhangsan
#  age: 18
#
#student: {id: 1,name: zhangsan,age: 20}