#server:
#  port: 8888
  #自定义配置项
#mytest1: 小黑

#数据库
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/demo1?characterEncoding=utf8
#    username: root
#    password: root
#字符串
#myStirng1: 哈喽\n呀
#myStirng2: '哈喽\n呀'
#myStirng3: "哈喽\n呀"

#student:
#  id: 1
#  name: zhangsan
#  age: 18

student: {id: 1,name: zhangsan,age: 20}